apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: distctr
servers: 1
agents: 0
image: rancher/k3s:v1.24.0-rc1-k3s1
network: nats-distctr_default
options:
  k3d:
    disableLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --datastore-endpoint=nats://distctr-cluster:distctr-cluster-pass@nats-1:4222/?bucket=distctr-cluster
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
