version: '3.8'

services:
  nats-1:
    image: nats:2.8.2-alpine
    hostname: nats-1
    networks:
    - default
    volumes:
    - ./${NATS_CONFIG}:/etc/nats/nats-server.conf
    - nats-1:/data

  nats-box:
    image: natsio/nats-box:0.11.0
    hostname: nats-box
    networks:
    - default
    environment:
      NATS_URL: nats://nats-box:nats-box-pass@nats-1:4222
    entrypoint:
      - sh
    command:
      - -c
      - trap "exit 0" SIGINT SIGTERM; while true; do sleep 0.1; done

networks:
  default: {}

volumes:
  nats-1: {}
