apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: eu-munich
servers: 1
agents: 0
image: rancher/k3s:v1.24.0-rc1-k3s1
network: nats-eu
options:
  k3d:
    disableLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable=metrics-server
        nodeFilters:
          - server:*
      - arg: --disable=local-storage
        nodeFilters:
          - server:*
      - arg: --datastore-endpoint=nats://munich:munich@nats-1:4222/?bucket=eu-munich
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
